###### 1.	Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

a1 = np.random.randint(0,10,(3,3))
a2 = np.random.randint(0,10,(3,3))

In [7]:
a1

array([[6, 7, 6],
       [7, 2, 1],
       [1, 0, 1]])

In [8]:
a2

array([[2, 0, 9],
       [4, 4, 8],
       [8, 4, 9]])

In [3]:
def add_matrix(a1,a2):
    return a1+a2

In [4]:
add_matrix(a1,a2)

array([[ 8,  7, 15],
       [11,  6,  9],
       [ 9,  4, 10]])

###### 2.	Write a Python Program to Multiply Two Matrices?

In [5]:
def multiply_matrix(a1,a2):
    return a1@a2

In [6]:
multiply_matrix(a1,a2)

array([[ 88,  52, 164],
       [ 30,  12,  88],
       [ 10,   4,  18]])

###### 3.	Write a Python Program to Transpose a Matrix?

In [10]:
def mat_trans(a1):
    return a1.T

In [11]:
mat_trans(a1)

array([[6, 7, 1],
       [7, 2, 0],
       [6, 1, 1]])

In [12]:
mat_trans(a2)

array([[2, 4, 8],
       [0, 4, 4],
       [9, 8, 9]])

###### 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [26]:
a = input("Please enter the string: ")
words = []
for i in a.split():
    words.append(i.lower())

words.sort()
for j in words:
    print(j)

Please enter the string: My NAme is sachin
is
my
name
sachin


###### 5.	Write a Python Program to Remove Punctuation From a String?

In [27]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
a = input("PLease enter the string: ")

res = ""
for i in a:
    if i not in punctuations:
        res = res+i

print(res)

PLease enter the string: My Name is Sachin Dev, dev sachin, @#$^GVDSK
My Name is Sachin Dev dev sachin GVDSK
