In [2]:
import pandas as pd

In [3]:
data = {
    'name': ["Sachin","Manna","Dev","Sharma"],
    'salary': [500,600,800,900],
    'mail_id':['sachin@abc.com','manna@abc.com','dev@abc.com','sharma@abc.com'],
    'address': ['lit','ind','lit','ind']
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

name  salary         mail_id address
0  Sachin     500  sachin@abc.com     lit
1   Manna     600   manna@abc.com     ind
2     Dev     800     dev@abc.com     lit
3  Sharma     900  sharma@abc.com     ind

In [6]:
##change column name
pd.DataFrame(data,columns = [0,1,2,3])

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [7]:
df

name  salary         mail_id address
0  Sachin     500  sachin@abc.com     lit
1   Manna     600   manna@abc.com     ind
2     Dev     800     dev@abc.com     lit
3  Sharma     900  sharma@abc.com     ind

In [9]:
##give index name
df = pd.DataFrame(data,index=[4,5,6,7])
df

name  salary         mail_id address
4  Sachin     500  sachin@abc.com     lit
5   Manna     600   manna@abc.com     ind
6     Dev     800     dev@abc.com     lit
7  Sharma     900  sharma@abc.com     ind

In [13]:
### loc look after named index
df.loc[5:6]

name  salary        mail_id address
5  Manna     600  manna@abc.com     ind
6    Dev     800    dev@abc.com     lit

In [14]:
##iloc look after default index
df.iloc[5:6]

Empty DataFrame
Columns: [name, salary, mail_id, address]
Index: []

In [17]:
df.iloc[1:3]

name  salary        mail_id address
5  Manna     600  manna@abc.com     ind
6    Dev     800    dev@abc.com     lit

In [18]:
df

name  salary         mail_id address
4  Sachin     500  sachin@abc.com     lit
5   Manna     600   manna@abc.com     ind
6     Dev     800     dev@abc.com     lit
7  Sharma     900  sharma@abc.com     ind

In [19]:
###give string vbased index
df = pd.DataFrame(data,index=["sachin","manna","dev","sharma"])
df

name  salary         mail_id address
sachin  Sachin     500  sachin@abc.com     lit
manna    Manna     600   manna@abc.com     ind
dev        Dev     800     dev@abc.com     lit
sharma  Sharma     900  sharma@abc.com     ind

In [21]:
df = pd.DataFrame(data,index = [0,1,2,3])
df

name  salary         mail_id address
0  Sachin     500  sachin@abc.com     lit
1   Manna     600   manna@abc.com     ind
2     Dev     800     dev@abc.com     lit
3  Sharma     900  sharma@abc.com     ind

In [22]:
data1 = {
    'pf_no': [234,562,452,42],
    "income_tax": [234,4564,123,2335],
    "mobile_no":[123,456,872,12313],
    "courses": ['ds','js','ai','java']
}

In [23]:
df1 = pd.DataFrame(data1)

In [24]:
df1

pf_no  income_tax  mobile_no courses
0    234         234        123      ds
1    562        4564        456      js
2    452         123        872      ai
3     42        2335      12313    java

In [25]:
df

name  salary         mail_id address
0  Sachin     500  sachin@abc.com     lit
1   Manna     600   manna@abc.com     ind
2     Dev     800     dev@abc.com     lit
3  Sharma     900  sharma@abc.com     ind

In [29]:
pd.concat([df,df1]) ###vertical concat

name  salary         mail_id address  pf_no  income_tax  mobile_no  \
0  Sachin   500.0  sachin@abc.com     lit    NaN         NaN        NaN   
1   Manna   600.0   manna@abc.com     ind    NaN         NaN        NaN   
2     Dev   800.0     dev@abc.com     lit    NaN         NaN        NaN   
3  Sharma   900.0  sharma@abc.com     ind    NaN         NaN        NaN   
0     NaN     NaN             NaN     NaN  234.0       234.0      123.0   
1     NaN     NaN             NaN     NaN  562.0      4564.0      456.0   
2     NaN     NaN             NaN     NaN  452.0       123.0      872.0   
3     NaN     NaN             NaN     NaN   42.0      2335.0    12313.0   

  courses  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
0      ds  
1      js  
2      ai  
3    java

In [30]:
###horizontal concat
### axis1 :- column wise
pd.concat([df,df1],axis=1)

name  salary         mail_id address  pf_no  income_tax  mobile_no  \
0  Sachin     500  sachin@abc.com     lit    234         234        123   
1   Manna     600   manna@abc.com     ind    562        4564        456   
2     Dev     800     dev@abc.com     lit    452         123        872   
3  Sharma     900  sharma@abc.com     ind     42        2335      12313   

  courses  
0      ds  
1      js  
2      ai  
3    java

In [31]:
data3 = {
    '0': [234,562,452,42],
    "1": [234,4564,123,2335],
    "2":[123,456,872,12313],
    "3": ['ds','js','ai','java']
}

data2 = {
    '0': ["Sachin","Manna","Dev","Sharma"],
    '1': [500,600,800,900],
    '2':['sachin@abc.com','manna@abc.com','dev@abc.com','sharma@abc.com'],
    '3': ['lit','ind','lit','ind']
}

In [32]:
df3 = pd.DataFrame(data3)
df2 = pd.DataFrame(data2)

In [35]:
df2

0    1               2    3
0  Sachin  500  sachin@abc.com  lit
1   Manna  600   manna@abc.com  ind
2     Dev  800     dev@abc.com  lit
3  Sharma  900  sharma@abc.com  ind

In [36]:
df3

0     1      2     3
0  234   234    123    ds
1  562  4564    456    js
2  452   123    872    ai
3   42  2335  12313  java

In [39]:
pd.concat([df2,df3])

0     1               2     3
0  Sachin   500  sachin@abc.com   lit
1   Manna   600   manna@abc.com   ind
2     Dev   800     dev@abc.com   lit
3  Sharma   900  sharma@abc.com   ind
0     234   234             123    ds
1     562  4564             456    js
2     452   123             872    ai
3      42  2335           12313  java

In [40]:
data4 = {
    'emp_id':[101,102,103,104],
    'salary':[100,200,300,400],
    'pf':[23,34,56,78],
}

In [41]:
data5 = {
    'emp_id':[101,102,104,105],
    'mobile_no':[10234,132453,6874,48674],
    "house_no":[345,415,423,897]
}

In [42]:
df4 = pd.DataFrame(data4)
df5 = pd.DataFrame(data5)

In [43]:
df4

emp_id  salary  pf
0     101     100  23
1     102     200  34
2     103     300  56
3     104     400  78

In [44]:
df5

emp_id  mobile_no  house_no
0     101      10234       345
1     102     132453       415
2     104       6874       423
3     105      48674       897

In [45]:
###merge

pd.merge(df4,df5)

emp_id  salary  pf  mobile_no  house_no
0     101     100  23      10234       345
1     102     200  34     132453       415
2     104     400  78       6874       423

In [47]:
pd.merge(df4,df5, how="left")

emp_id  salary  pf  mobile_no  house_no
0     101     100  23    10234.0     345.0
1     102     200  34   132453.0     415.0
2     103     300  56        NaN       NaN
3     104     400  78     6874.0     423.0

In [48]:
pd.merge(df4,df5, how="right")

emp_id  salary    pf  mobile_no  house_no
0     101   100.0  23.0      10234       345
1     102   200.0  34.0     132453       415
2     104   400.0  78.0       6874       423
3     105     NaN   NaN      48674       897

In [49]:
pd.merge(df4,df5, how="right",on='emp_id')

emp_id  salary    pf  mobile_no  house_no
0     101   100.0  23.0      10234       345
1     102   200.0  34.0     132453       415
2     104   400.0  78.0       6874       423
3     105     NaN   NaN      48674       897

In [50]:
data6 = {
    'emp_id1':[101,102,103,104],
    'salary':[100,200,300,400],
    'pf':[23,34,56,78],
}

In [51]:
data7 = {
    'emp_id2':[101,102,104,105],
    'mobile_no':[10234,132453,6874,48674],
    "house_no":[345,415,423,897]
}

In [52]:
df6 = pd.DataFrame(data6)
df7 = pd.DataFrame(data7)

In [54]:
pd.merge(df6,df7)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [56]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2')

emp_id1  salary  pf  emp_id2  mobile_no  house_no
0      101     100  23      101      10234       345
1      102     200  34      102     132453       415
2      104     400  78      104       6874       423

In [63]:
data8 = {
    'emp_id':[101,102,103,104],
    'salary':[100,200,300,400],
    'pf':[23,34,56,78],
}
data9 = {
    'emp_id':[101,102,104,105],
    'salary':[100,132453,400,48674],
    "house_no":[345,415,423,897]
}

In [64]:
df8 = pd.DataFrame(data8)
df9 = pd.DataFrame(data9)

In [65]:
df8

emp_id  salary  pf
0     101     100  23
1     102     200  34
2     103     300  56
3     104     400  78

In [66]:
df9

emp_id  salary  house_no
0     101     100       345
1     102  132453       415
2     104     400       423
3     105   48674       897

In [67]:
##merge on different columns
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_no
0     101     100  23       345
1     104     400  78       423

In [68]:
data9 = {
    'emp_id':[101,102,104,105,106],
    'salary':[100,132453,400,48674,154],
    "house_no":[345,415,423,897,16541]
}

In [69]:
pd.merge(df8,df9,on=['emp_id','salary'])

emp_id  salary  pf  house_no
0     101     100  23       345
1     104     400  78       423

In [86]:
data10 = {
    'emp_id1':[101,102,103,104],
    'salary1':[100,200,300,400],
    'pf':[23,34,56,78],
}
data11 = {
    'emp_id2':[101,102,104,105,106],
    'salary2':[100,132453,400,48674,1456],
    "house_no":[345,415,423,897,4785]
}

In [87]:
df10 = pd.DataFrame(data10,index=['a','b','c','d'])
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [88]:
df10

emp_id1  salary1  pf
a      101      100  23
b      102      200  34
c      103      300  56
d      104      400  78

In [89]:
df11

emp_id2  salary2  house_no
a      101      100       345
b      102   132453       415
d      104      400       423
e      105    48674       897
f      106     1456      4785

In [91]:
## default is left join
## it joins the data in indexes while merge join the data based on columns
df10.join(df11)  

emp_id1  salary1  pf  emp_id2   salary2  house_no
a      101      100  23    101.0     100.0     345.0
b      102      200  34    102.0  132453.0     415.0
c      103      300  56      NaN       NaN       NaN
d      104      400  78    104.0     400.0     423.0

In [93]:
df10.join(df11,how='inner')

emp_id1  salary1  pf  emp_id2  salary2  house_no
a      101      100  23      101      100       345
b      102      200  34      102   132453       415
d      104      400  78      104      400       423

In [95]:
df_sales = pd.read_csv("sales_data_final.csv")

In [96]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [97]:
df_sales.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

In [99]:
df_sales.dtypes

order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_name      object
segment            object
state              object
country            object
market             object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales              object
quantity            int64
discount          float64
profit            float64
shipping_cost     float64
order_priority     object
year                int64
dtype: object

In [101]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   order_id        51290 non-null  object 
 1   order_date      51290 non-null  object 
 2   ship_date       51290 non-null  object 
 3   ship_mode       51290 non-null  object 
 4   customer_name   51290 non-null  object 
 5   segment         51290 non-null  object 
 6   state           51290 non-null  object 
 7   country         51290 non-null  object 
 8   market          51290 non-null  object 
 9   region          51290 non-null  object 
 10  product_id      51290 non-null  object 
 11  category        51290 non-null  object 
 12  sub_category    51290 non-null  object 
 13  product_name    51290 non-null  object 
 14  sales           51290 non-null  object 
 15  quantity        51290 non-null  int64  
 16  discount        51290 non-null  float64
 17  profit          51290 non-null 

In [102]:
df_sales.describe()

quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

In [103]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [104]:
##if profit is +ve then profitflag = POSITIVE else profit_flag = NEGATIVE

In [107]:
def profit_flag(a):
    if a>=0:
        return 'Positive'
    else:
        return 'Negative'

In [108]:
profit_flag(-26)

'Negative'

In [109]:
profit_flag(26)

'Positive'

In [111]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [112]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    Positive  
1           9.72          Medium  2011    Positive  
2           8.17            High  2011    Positive  
3           4.82            High  2011    Negative  
4           4.70          Medium  2011    Positive  

[5 rows x 22 columns]

In [114]:
##create column to store length of customer name
df_sales['len_cyst_name'] = df_sales['customer_name'].apply(len)

In [115]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cyst_name  
0          35.46          Medium  2011     Positive            15  
1           9.72          Medium  2011     Positive            11  
2           8.17            High  2011     Positive            13  
3           4.82            High  2011     Negative            12  
4           4.70          Medium  2011     Positive            11  

[5 rows x 23 columns]

In [117]:
df_sales['quantity'].unique()

array([ 2,  3,  4,  5,  1,  7,  6,  8,  9, 10, 11, 12, 14, 13],
      dtype=int64)

In [118]:
## qunatity b/w 0 to 5 low, 6-10 meduim , above 10 high
def quantity_flag(a):
    if a < 5:
        return "low"
    elif a>5 and a<11:
        return "medium"
    else:
        return "high"

In [119]:
df_sales["quantity_flag"] = df_sales['quantity'].apply(quantity_flag)

In [120]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     Positive   
1        3      0.1   36.036          9.72          Medium  2011     Positive   
2        4      0.0   29.640          8.17            High  2011     Positive   
3        3      0.5  -26.055          4.82            High  2011     Negative   
4        5      0.1   37.770          4.70          Medium  2011     Positive   

   len_cyst_name quantity_flag  
0             15           low  
1             11           low  
2             13           low  
3             12           low  
4             11          high  

[5 rows x 24 columns]

In [121]:
##using lambda func
df_sales["quantity_sqaure"] = df_sales['quantity'].apply(lambda x: x**2)

In [122]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     Positive   
1      0.1   36.036          9.72         Medium  2011     Positive   
2      0.0   29.640          8.17           High  2011     Positive   
3      0.5  -26.055          4.82           High  2011     Negative   
4      0.1   37.770          4.70         Medium  2011     Positive   

   len_cyst_name  quantity_flag quantity_sqaure  
0             15            low               4  
1             11            low               9  
2             13            low              16  
3             12            low               9  
4             11           high              25  

[5 rows x 25 columns]

In [123]:
import numpy as np

In [124]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [125]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [126]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [127]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [128]:
l = np.array([[1,2,3,4],[2,3,4,5]])

In [129]:
l

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [130]:
l[0]

array([1, 2, 3, 4])

In [131]:
l[1]

array([2, 3, 4, 5])

In [132]:
l[0][0]

1

In [134]:
## dimension is 5
a = np.array([3,4,5,6], ndmin = 5)
a

array([[[[[3, 4, 5, 6]]]]])

In [135]:
a = np.array([3,4,5,6], ndmin = 3)
a

array([[[3, 4, 5, 6]]])

In [136]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
##hceck dimension of array
arr.ndim

2

In [141]:
##generate random dataset biw 1to10 with dimension 4by4
## 4x4 ==> 4rows and 4columns
arr = np.random.randint(1,10,(4,4))

In [142]:
arr

array([[7, 6, 3, 2],
       [1, 6, 1, 5],
       [3, 5, 3, 7],
       [8, 5, 7, 3]])

In [143]:
arr.ndim

2

In [147]:
##total num of ele generated = 4*4*2 = 32
## 4 x 4 x 2  ====> 4 (4x2) ==> so we have 4x2 arrays 4times
arr = np.random.randint(1,10,(4,4,2))

In [148]:
arr

array([[[4, 4],
        [6, 9],
        [4, 7],
        [1, 3]],

       [[8, 2],
        [2, 4],
        [1, 7],
        [2, 6]],

       [[7, 8],
        [8, 7],
        [1, 8],
        [1, 2]],

       [[1, 5],
        [9, 2],
        [5, 6],
        [5, 7]]])

In [149]:
arr.ndim

3