In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5,6]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [4]:
l1 = [4,2,3,6,'sachin',1.2213,True]

In [5]:
np.array(l1)

array(['4', '2', '3', '6', 'sachin', '1.2213', 'True'], dtype='<U11')

In [6]:
np.array([1,2,3,45,5+6j])

array([ 1.+0.j,  2.+0.j,  3.+0.j, 45.+0.j,  5.+6.j])

In [7]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
###3D Array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
a1 = np.array(l1)

In [16]:
a2 = np.array([[1,2,3],[4,5,6]])

In [17]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [18]:
a1

array(['4', '2', '3', '6', 'sachin', '1.2213', 'True'], dtype='<U11')

In [19]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

###### get dimension of an array

In [22]:
a1.ndim

1

In [23]:
a2.ndim

2

In [24]:
a3.ndim

3

###### size of array(num of elements in array)

In [25]:
a1.size

7

In [26]:
a2.size

6

In [27]:
a3.size

9

###### shape of an array

In [28]:
a1.shape

(7,)

In [29]:
a2.shape

(2, 3)

In [30]:
a3.shape

(1, 3, 3)

In [31]:
type(a1.shape)

tuple

In [32]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
a3.shape

(1, 3, 3)

(1,3,3) ---> 1(3x3) ---> 1Array of 3x3 shape

In [35]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a2.shape

(2, 3)

(2,3) ---> 2 rows and 3 columns

###### generate random data

In [37]:
##random num b/w 2and 4
np.random.randint(2,5)

3

In [39]:
##random num b/w 2and 49
np.random.randint(2,50)

15

In [41]:
### generate data in specific dimension
np.random.randint(2,50,(3,4))

array([[15, 38, 42, 43],
       [33,  8, 36, 48],
       [15, 41,  9,  7]])

In [42]:
np.random.randint(2,50,(3,4,4))

array([[[11, 33, 33, 20],
        [19, 20, 11,  5],
        [40, 27, 46, 14],
        [46, 10, 10, 43]],

       [[45, 47, 13, 37],
        [42,  5,  5, 35],
        [ 6, 33, 23, 28],
        [28, 25, 33, 42]],

       [[46, 36, 48,  8],
        [44, 15, 35, 29],
        [24, 10, 24, 48],
        [ 8, 48, 37, 35]]])

In [43]:
np.random.randint(2,50,(2,3))

array([[30,  9, 27],
       [20, 27, 20]])

In [44]:
np.random.randint(2,50,(3,3))

array([[19, 17, 28],
       [18,  8, 31],
       [40, 39,  4]])

In [45]:
np.random.rand(2,3)

array([[0.56992415, 0.77683838, 0.30437454],
       [0.36220047, 0.55717032, 0.83570917]])

In [47]:
##randn
np.random.randn(4,4)

array([[ 0.78583566, -0.35786634,  2.03984345, -0.22736088],
       [-0.50390148, -0.24398764, -0.29600236,  0.38286132],
       [ 0.79389218,  1.37273936, -0.60370658,  1.52812689],
       [-0.62042123, -0.25350337, -0.64325094,  0.65102595]])

###### np.rand vs np.randn

 numpy.random.randn generates samples from the normal distribution, while numpy.random.rand from a uniform distribution

###### change the shape of an array

In [48]:
a4 = np.random.randn(4,4)

In [49]:
a4

array([[ 0.9294149 ,  1.62775415,  0.83412113, -0.71121064],
       [-0.29243985, -1.97869677, -1.13358613,  0.40941672],
       [-0.07670861,  0.89792278,  0.62874224, -0.41383258],
       [-0.03008348,  0.84035207, -1.54382902, -0.94770279]])

In [51]:
a4.reshape(3,4)

ValueError: cannot reshape array of size 16 into shape (3,4)

In [52]:
a4.reshape(2,8)

array([[ 0.9294149 ,  1.62775415,  0.83412113, -0.71121064, -0.29243985,
        -1.97869677, -1.13358613,  0.40941672],
       [-0.07670861,  0.89792278,  0.62874224, -0.41383258, -0.03008348,
         0.84035207, -1.54382902, -0.94770279]])

In [53]:
a4.reshape(8,2)

array([[ 0.9294149 ,  1.62775415],
       [ 0.83412113, -0.71121064],
       [-0.29243985, -1.97869677],
       [-1.13358613,  0.40941672],
       [-0.07670861,  0.89792278],
       [ 0.62874224, -0.41383258],
       [-0.03008348,  0.84035207],
       [-1.54382902, -0.94770279]])

In [54]:
a4.reshape(16,1)

array([[ 0.9294149 ],
       [ 1.62775415],
       [ 0.83412113],
       [-0.71121064],
       [-0.29243985],
       [-1.97869677],
       [-1.13358613],
       [ 0.40941672],
       [-0.07670861],
       [ 0.89792278],
       [ 0.62874224],
       [-0.41383258],
       [-0.03008348],
       [ 0.84035207],
       [-1.54382902],
       [-0.94770279]])

In [55]:
a4.reshape(1,16)

array([[ 0.9294149 ,  1.62775415,  0.83412113, -0.71121064, -0.29243985,
        -1.97869677, -1.13358613,  0.40941672, -0.07670861,  0.89792278,
         0.62874224, -0.41383258, -0.03008348,  0.84035207, -1.54382902,
        -0.94770279]])

In [62]:
## when we give -ve num then numpy is able to detect the factorial
a4.reshape(2,-1)

array([[ 0.9294149 ,  1.62775415,  0.83412113, -0.71121064, -0.29243985,
        -1.97869677, -1.13358613,  0.40941672],
       [-0.07670861,  0.89792278,  0.62874224, -0.41383258, -0.03008348,
         0.84035207, -1.54382902, -0.94770279]])

In [63]:
a4.reshape(-50,2)

array([[ 0.9294149 ,  1.62775415],
       [ 0.83412113, -0.71121064],
       [-0.29243985, -1.97869677],
       [-1.13358613,  0.40941672],
       [-0.07670861,  0.89792278],
       [ 0.62874224, -0.41383258],
       [-0.03008348,  0.84035207],
       [-1.54382902, -0.94770279]])

In [64]:
a4.reshape(2,2,4)

array([[[ 0.9294149 ,  1.62775415,  0.83412113, -0.71121064],
        [-0.29243985, -1.97869677, -1.13358613,  0.40941672]],

       [[-0.07670861,  0.89792278,  0.62874224, -0.41383258],
        [-0.03008348,  0.84035207, -1.54382902, -0.94770279]]])

In [65]:
a4.reshape(2,2,-1)

array([[[ 0.9294149 ,  1.62775415,  0.83412113, -0.71121064],
        [-0.29243985, -1.97869677, -1.13358613,  0.40941672]],

       [[-0.07670861,  0.89792278,  0.62874224, -0.41383258],
        [-0.03008348,  0.84035207, -1.54382902, -0.94770279]]])

In [68]:
a4.reshape(1,1,1,1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[[[[ 0.9294149 ,  1.62775415,  0.83412113,
                   -0.71121064],
                  [-0.29243985, -1.97869677, -1.13358613,
                    0.40941672]],

                 [[-0.07670861,  0.89792278,  0.62874224,
                   -0.41383258],
                  [-0.03008348,  0.84035207, -1.54382902,
                   -0.94770279]]]]]]]]]]]]])

###### Extract data from an array

In [71]:
a1

array(['4', '2', '3', '6', 'sachin', '1.2213', 'True'], dtype='<U11')

In [72]:
a1.shape

(7,)

In [74]:
a1[-1]

'True'

In [75]:
a1[0]

'4'

In [76]:
a1[2::]

array(['3', '6', 'sachin', '1.2213', 'True'], dtype='<U11')

In [78]:
a1[2:6]

array(['3', '6', 'sachin', '1.2213'], dtype='<U11')

In [79]:
a1[2:6:2]

array(['3', 'sachin'], dtype='<U11')

In [80]:
##reverese array
a1[::-1]

array(['True', '1.2213', 'sachin', '6', '3', '2', '4'], dtype='<U11')

In [81]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [82]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
a2[0]

array([1, 2, 3])

In [89]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [91]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [92]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [99]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
##extract 1 and 6 from a2
## [0,0] --> 1 and [1,2] --> 6
## a2[0th row,1st row],[0th column, 2nd column]
a2[[0,1],[0,2]]

array([1, 6])

###### filter data from array and change values of elements

In [106]:
a5 = np.random.randint(2,90,(6,5))

In [107]:
a5

array([[ 4, 77, 42, 46, 61],
       [29, 47, 71, 33, 85],
       [66, 36, 16, 81,  2],
       [40, 42, 82, 56, 23],
       [40, 52, 26, 81, 87],
       [63, 70, 82, 26, 56]])

In [108]:
##filter that with value more than 40

a5[a5>40]

array([77, 42, 46, 61, 47, 71, 85, 66, 81, 42, 82, 56, 52, 81, 87, 63, 70,
       82, 56])

In [109]:
a5

array([[ 4, 77, 42, 46, 61],
       [29, 47, 71, 33, 85],
       [66, 36, 16, 81,  2],
       [40, 42, 82, 56, 23],
       [40, 52, 26, 81, 87],
       [63, 70, 82, 26, 56]])

In [111]:
### change 77 to 50
a5[0,1] = 50

In [112]:
a5

array([[ 4, 50, 42, 46, 61],
       [29, 47, 71, 33, 85],
       [66, 36, 16, 81,  2],
       [40, 42, 82, 56, 23],
       [40, 52, 26, 81, 87],
       [63, 70, 82, 26, 56]])

###### Arithmetic Operation

In [122]:
a6 = np.random.randint(0,3,(3,3))

In [123]:
a6

array([[0, 0, 2],
       [0, 0, 2],
       [2, 2, 0]])

In [124]:
a7 = np.random.randint(0,3,(3,3))

In [125]:
a7

array([[0, 1, 2],
       [2, 2, 2],
       [0, 2, 0]])

In [126]:
a6*a7

array([[0, 0, 4],
       [0, 0, 4],
       [0, 4, 0]])

here it's doing multiplication of element by element and not matrix multiplication

In [127]:
a6+a7

array([[0, 1, 4],
       [2, 2, 4],
       [2, 4, 0]])

In [131]:
a6*2

array([[0, 0, 4],
       [0, 0, 4],
       [4, 4, 0]])

In [132]:
a6+100

array([[100, 100, 102],
       [100, 100, 102],
       [102, 102, 100]])

In [133]:
a6/2

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [134]:
a6/0

<ipython-input-134-fb79fded0e91>:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
<ipython-input-134-fb79fded0e91>:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, nan, inf],
       [nan, nan, inf],
       [inf, inf, nan]])

In [135]:
a6**3

array([[0, 0, 8],
       [0, 0, 8],
       [8, 8, 0]], dtype=int32)

###### Matrix Multiplication

In [128]:
a6@a7

array([[0, 4, 0],
       [0, 4, 0],
       [4, 6, 8]])

In [130]:
np.dot(a6,a7)

array([[0, 4, 0],
       [0, 4, 0],
       [4, 6, 8]])

###### special arrays

In [137]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [143]:
a9 = np.ones((4,5))

In [144]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [146]:
a9.shape

(4, 5)

In [147]:
a9.ndim

2

In [149]:
##broadcasting
a9 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [150]:
a9 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [153]:
##transpose
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [154]:
##column wise operation
a9+ np.array([1,2,3,4]).T

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [155]:
np.array([1,2,3,4]).T + a9

ValueError: operands could not be broadcast together with shapes (4,) (4,5) 

In [156]:
##in order to transpose we need atleast 2 dimensions

np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [159]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [160]:
a6

array([[0, 0, 2],
       [0, 0, 2],
       [2, 2, 0]])

In [161]:
a6.T

array([[0, 0, 2],
       [0, 0, 2],
       [2, 2, 0]])

In [162]:
a5

array([[ 4, 50, 42, 46, 61],
       [29, 47, 71, 33, 85],
       [66, 36, 16, 81,  2],
       [40, 42, 82, 56, 23],
       [40, 52, 26, 81, 87],
       [63, 70, 82, 26, 56]])

In [163]:
##find sqrt of each element
np.sqrt(a5)

array([[2.        , 7.07106781, 6.4807407 , 6.78232998, 7.81024968],
       [5.38516481, 6.8556546 , 8.42614977, 5.74456265, 9.21954446],
       [8.1240384 , 6.        , 4.        , 9.        , 1.41421356],
       [6.32455532, 6.4807407 , 9.05538514, 7.48331477, 4.79583152],
       [6.32455532, 7.21110255, 5.09901951, 9.        , 9.32737905],
       [7.93725393, 8.36660027, 9.05538514, 5.09901951, 7.48331477]])

In [164]:
## find exponent of each element
np.exp(a5)

array([[5.45981500e+01, 5.18470553e+21, 1.73927494e+18, 9.49611942e+19,
        3.10429794e+26],
       [3.93133430e+12, 2.58131289e+20, 6.83767123e+30, 2.14643580e+14,
        8.22301271e+36],
       [4.60718663e+28, 4.31123155e+15, 8.88611052e+06, 1.50609731e+35,
        7.38905610e+00],
       [2.35385267e+17, 1.73927494e+18, 4.09399696e+35, 2.09165950e+24,
        9.74480345e+09],
       [2.35385267e+17, 3.83100800e+22, 1.95729609e+11, 1.50609731e+35,
        6.07603023e+37],
       [2.29378316e+27, 2.51543867e+30, 4.09399696e+35, 1.95729609e+11,
        2.09165950e+24]])

In [165]:
np.log10(a5)

array([[0.60205999, 1.69897   , 1.62324929, 1.66275783, 1.78532984],
       [1.462398  , 1.67209786, 1.85125835, 1.51851394, 1.92941893],
       [1.81954394, 1.5563025 , 1.20411998, 1.90848502, 0.30103   ],
       [1.60205999, 1.62324929, 1.91381385, 1.74818803, 1.36172784],
       [1.60205999, 1.71600334, 1.41497335, 1.90848502, 1.93951925],
       [1.79934055, 1.84509804, 1.91381385, 1.41497335, 1.74818803]])

In [168]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [169]:
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [170]:
np.arange(0,10,2.5)

array([0. , 2.5, 5. , 7.5])

In [172]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [173]:
np.arange(7.8,12.5,2.5)

array([ 7.8, 10.3])

In [174]:
## generate 50nums b/w 2 and 3
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [175]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

step size was 0.02040816326530612

In [176]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [177]:
### identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])